### ISSUE TITLE
2.0.11 php error

### ISSUE THREAD

**Issue by Stoatwblr** [ericferon/glpi-statecheck#11]
Immediately after unpacking the 2.0.11 tarball, when going to the plugins page - before install

[2019-02-01 00:25:53] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginStatecheckRule::executePluginsActions($action, $output, $params) should be compatible with Rule::executePluginsActions($action, $output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365
  inc/autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  plugins/statecheck/inc/menu.class.php:40           spl_autoload_call()
  inc/html.class.php:1426                            PluginStatecheckMenu::getMenuContent()
  inc/html.class.php:6190                            Html::generateMenuSession()
  inc/html.class.php:1530                            Html::displayMainMenu()
  front/plugin.php:89                                Html::header()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}
[2019-02-01 00:25:53] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginStatecheckRule::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365
  inc/autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  plugins/statecheck/inc/menu.class.php:40           spl_autoload_call()
  inc/html.class.php:1426                            PluginStatecheckMenu::getMenuContent()
  inc/html.class.php:6190                            Html::generateMenuSession()
  inc/html.class.php:1530                            Html::displayMainMenu()
  front/plugin.php:89                                Html::header()
  {"user":"11@msslyz.mssl.ucl.ac.uk","mem_usage":"0.001\", 8.10Mio)"}

**Comment by ericferon** [comment]
Solved in v2.0.12
Thank you for your remark,

**Comment by Stoatwblr** [comment]
Unfortunately not. It's still happening.

/usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginStatecheckRule::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365                      
  inc/autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  plugins/statecheck/inc/menu.class.php:40           spl_autoload_call()
  inc/html.class.php:1426                            PluginStatecheckMenu::getMenuContent()
  inc/html.class.php:6190                            Html::generateMenuSession()
  inc/html.class.php:1530                            Html::displayMainMenu()
  front/plugin.php:89                                Html::header()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}

**Comment by ericferon** [comment]
Which GLPI version and plugin version are you using ?
Best regards,
